### ISSUE TITLE
Small Correction to 1.0 RC1

### ISSUE THREAD

**Issue by dougwinsby** [sandpiper-framework/sandpiper-schemas#12]
In the **Granulation Strategies for ACES** section, 4th paragraph, it says:

>"In versions of ACES lower than 4.0 this is the only opportunity to indicate the branding of the
parts (via the  BrandAAIAID  element); from 4.0 onwards branding can also be specified as an attribute of
the  Part  element."

This is not correct. BrandAAIAID was added to Part element in ACES 3.0 (5/26/2009).

**Comment by kristerk** [comment]
Thank you for catching this. I got turned around on the subbrand code at some point and conflated that with the brand code on the part element. I've corrected and will merge into main with the 1.0.0-FINAL!
